### ISSUE TITLE
All features running when i pass input as specific tags

### ISSUE THREAD

**Issue by jakjothi** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#10]
`./node_modules/.bin/protractor protractor.conf.js --tags=@SearchCompanies`

Only specified tags feature should run instead of all features

**Comment by wswebcreation** [comment]
@jakjothi 

sorry, but this is not related to the module but the way you call the tags You should use `--cucumberOpts.tags @SearchCompanies`.

Please ask usage or issues with other frameworks / modules on the repo of the framework / on stackoverflow
