### ISSUE TITLE
customMetaData

### ISSUE THREAD

**Issue by Rob-Meijeren** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#11]
Hello,

I would like to use the customMetaData property of the multiple-cucumber-html-reporter module with this plugin. My thought would then be that this is connected to the metadataKey. If this would be defined by the user to take over the metadata setup that would be defined there instead of the default that is always used right now.

Regards,

Rob

**Comment by wswebcreation** [comment]
Hi @Rob-Meijeren 

Isn't [this](https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#customdata) what you mean?

**Comment by Rob-Meijeren** [comment]
Hi Wim,

No that wasn't what I meant as that is creating an extra block and I would like to edit an existing block. 
Currently I have the following as my metadata (I added to the config of the plugin that it should look for deviceProperties instead of metadatakey):
![properties](https://user-images.githubusercontent.com/5420918/36476181-6837b28c-16fd-11e8-940a-4cd6f5c845af.PNG)
When I run my tests with this I have the following report:
![not-ok](https://user-images.githubusercontent.com/5420918/36476203-77372164-16fd-11e8-94e6-8544d4a17c22.PNG)
But I would like to see it like this:
![ok](https://user-images.githubusercontent.com/5420918/36476217-817970be-16fd-11e8-8b63-2c2508fd164c.PNG)
Now the reason this is different is because of instead of having a platform property in my metadata I have a os property with the same data. Since this module uses multiple-html-reporter I would like to use the option of them described here https://github.com/wswebcreation/multiple-cucumber-html-reporter#custommetadata. by setting the boolean and then adding the metadata the user has defined in their metadata (in this case deviceProperties) I should get a proper report without the question marks.

**Comment by wswebcreation** [comment]
Hi @Rob-Meijeren 

Sorry for my late response, I'm a bit busy the last weeks. If you like you may create a PR for it, else I pick this up in the upcoming weeks

**Comment by wswebcreation** [comment]
Added this option in version [1.5.0](https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin/blob/master/CHANGELOG.md#150-2018-03-05).

I'm going to close it for now, if it's still an issue please reopen this one or open a new issue
