### ISSUE TITLE
Error "Fail:  protractor-multiple-cucumber-html-reporter-plugin Runtime" when the json-output-folder is empty

### ISSUE THREAD

**Issue by vignesh-paramasivam** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#14]
HTML and JSON report is getting created successfully, still getting the error "Fail:  protractor-multiple-cucumber-html-reporter-plugin Runtime" when the json-output-folder is empty

This error is not getting occurred when there is atleast one json file is present inside web\json\json-output-folder.

**conf.js**
--------------------------------
```
cucumberOpts: {
    strict: true,
    require: step_definitions,
    tags: test_tags,
    format: ['json:./web/json/results.json'],
    profile: false,
    keepAlive: false,
    'no-source': true
  },
  
  plugins: [{
    package: 'protractor-multiple-cucumber-html-reporter-plugin',
    options:{
      // read the options part for more options
      automaticallyGenerateReport: true,
      removeExistingJsonReportFile: true
    }
  }]
```

 **Stacktrace**
 --------------------------------
```
[20:18:28] I/testLogger - [chrome #01-1] PID: 9240
[chrome #01-1] Specs: C:\Repo\application\testautomation\test\features\test_framework\login\test.feature
[chrome #01-1] 
[chrome #01-1] (node:9240) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[chrome #01-1] [20:18:22] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[chrome #01-1] [20:18:28] I/plugins -  	 Fail:  protractor-multiple-cucumber-html-reporter-plugin Runtime 
[chrome #01-1] [20:18:28] E/plugins - 		Failure during postResults: No JSON files found in 'web\json\json-output-folder'. NO REPORT CAN BE CREATED!
[chrome #01-1] [20:18:28] E/plugins - 		Error: No JSON files found in 'web\json\json-output-folder'. NO REPORT CAN BE CREATED!
[chrome #01-1] 		    at collectJSONS (C:\Repo\application\testautomation\test\node_modules\multiple-cucumber-html-reporter\lib\collect-jsons.js:19:15)
[chrome #01-1] 		    at Object.generateReport [as generate] (C:\Repo\application\testautomation\test\node_modules\multiple-cucumber-html-reporter\lib\generate-report.js:67:23)
[chrome #01-1] 		    at Object.postResults (C:\Repo\application\testautomation\test\node_modules\protractor-multiple-cucumber-html-reporter-plugin\index.js:289:43)
[chrome #01-1] 		    at resolver (C:\Repo\application\testautomation\test\node_modules\protractor\built\plugins.js:194:51)
[chrome #01-1] 		    at Function.promise (C:\Repo\application\testautomation\test\node_modules\q\q.js:682:9)
[chrome #01-1] 		    at Plugins.safeCallPluginFun (C:\Repo\application\testautomation\test\node_modules\protractor\built\plugins.js:207:22)
[chrome #01-1] 		    at promises.pluginObjs.filter.map.pluginObj (C:\Repo\application\testautomation\test\node_modules\protractor\built\plugins.js:219:40)
[chrome #01-1] 		    at Array.map (<anonymous>)
[chrome #01-1] 		    at Plugins.args [as postResults] (C:\Repo\application\testautomation\test\node_modules\protractor\built\plugins.js:219:18)
[chrome #01-1] 		    at q.then.then.then.then.then.then.then.then (C:\Repo\application\testautomation\test\node_modules\protractor\built\runner.js:432:28)
[chrome #01-1] 		    at _fulfilled (C:\Repo\application\testautomation\test\node_modules\q\q.js:834:54)
[chrome #01-1] 		    at self.promiseDispatch.done (C:\Repo\application\testautomation\test\node_modules\q\q.js:863:30)
[chrome #01-1] 		    at Promise.promise.promiseDispatch (C:\Repo\application\testautomation\test\node_modules\q\q.js:796:13)
[chrome #01-1] 		    at C:\Repo\application\testautomation\test\node_modules\q\q.js:604:44
[chrome #01-1] 		    at runSingle (C:\Repo\application\testautomation\test\node_modules\q\q.js:137:13)
[chrome #01-1] 		    at flush (C:\Repo\application\testautomation\test\node_modules\q\q.js:125:13)
```

**Comment by wswebcreation** [comment]
Hi @vignesh-paramasivam 

If there are no JSON-files this is correct behaviour. Can you also give an example when this happens exactly?

**Comment by vignesh-paramasivam** [comment]
While executing the test for the first time, the error occurs, as the actual report folder is empty before test. 
Looking at the error, it states JSON file is not created and throws error. But the json is created, and the html report is also get generated.
So my assumption is It checks for the json file before creating it and throws error, and then it ignores the error and continues in generating the html report. 
Note: 1.This error is not making the test to fail.2.It happens only when I set the report generation to true under options in plugins config.
Thanks,VigneshSent from Yahoo Mail on Android 
 
  On Thu, 14 Jun 2018 at 8:38 pm, Wim Selles<notifications@github.com> wrote:   
Hi @vignesh-paramasivam

If there are no JSON-files this is correct behaviour. Can you also give an example when this happens exactly?

**Comment by vignesh-paramasivam** [comment]
@wswebcreation The error occurs when i'm executing two feature files, where one of the feature file has all the scenarios ignore(@ignore) in it. So, the JSON is not getting created for that feature which has no scenarios to run.

I believe we need to create a json file for each feature file, even if all scenarios has ignored in it.

**Comment by wswebcreation** [comment]
Hi @vignesh-paramasivam 

Tnx for the explanation, this makes it more clear. I think I need to fix this in the `multiple-cucumber-html-reporter`. It now throws an error when it doesn't find any file. 
Because I can't generate the report at the end of all instances from Protractor, it will run it after each feature file. Because the first file doesn't create a file it will fail.

I'll pick this up this week and push a change on both the modules.

Tnx for catching!

**Comment by wswebcreation** [comment]
Has been fixed
