### ISSUE TITLE
Sort feature files based on sequence of execution

### ISSUE THREAD

**Issue by VenkatSaripilli** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#17]
Hi, 
First I should say the reporter looks awesome. I am using this for my reports. 

I have a question regarding the way the feature files are sorted by default.

I see the feature files in the report are sorted based on the name of the feature. 

I have several projects running and would like to see the feature files in the report appear in the same order, of how they executed.

Ex:  If the feature files are executing in the order below, I would like to see the same order in the report.
Feature 1
Feature 2
Feature 4
Feature 3

**Comment by wswebcreation** [comment]
Hi @VenkatSaripilli,

Initially this is not possible. What this module does is:
- provide you a way with Protractor to export the Jason files
- make a nice report based on the Jason files in a folder

The reporter itself doesn't have notice of the time features were executed. This plugin also does not have that info

Secondly I don't see a added value for showing the data in that way, but you can create a PR on the reporting module if you'd like

I'm going to close it for now, it's still open for discussion

Grtz

Wim
