### ISSUE TITLE
add mili or nano seconds Time in report 

### ISSUE THREAD

**Issue by chiragmatkar** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#19]
Time in report seems confusing and looks like HH::MM:SS format as it is not mentioned mili or nano seconds in report.Please add this to the report

**Comment by wswebcreation** [comment]
Hi @chiragmatkar

Can you please explain a little bit more what you mean?

By the way, this module is only a binding between Protractor and the report module that can be found here.

https://github.com/wswebcreation/multiple-cucumber-html-reporter

If there are issues with the report please file them there.

I'm going to close it here, tnx
