### ISSUE TITLE
When testing multiple OS's against the same Browser and Version only one is reported - OS not considered for unique entry

### ISSUE THREAD

**Issue by kiche777** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#2]
I'm using SauceLabs to execute various Browser/OS combinations and I find that whenever the Browser and Version are the same different OS's are not being displayed in the report.  It appears the last OS result wins and gets reported and therefore suggests OS is not considered to generate a unique entry.

For example the config below I have seen only Windows 8.1 reported or Windows 7 but not both in the same report.  This is confirmed by looking at the merged-output.json and enriched-output.json files where the other test runs are missing.

Ideally we would consider the OS as another unique entry and report it.

Example Config:
```js
      {
            'tunnel-identifier': tunnelID,
            build: buildNum,
            name: testRunName + '-Chrome51-Windows10',
            browserName: 'Chrome',
            version: '51.0',
            platform: 'Windows 10',
            screenResolution: screenResolution,
            // Metadata required for multiple reporter
            metadata: {
                browser: {
                    name: 'Chrome',
                    version: '51'
                },
                device: 'PC',
                platform: {
                    name: 'Windows',
                    version: '10'
                }
            }
        },
        {
            'tunnel-identifier': tunnelID,
            build: buildNum,
            name: testRunName + '-Chrome51-Windows8v1',
            browserName: 'Chrome',
            version: '51.0',
            platform: 'Windows 8.1',
            screenResolution: screenResolution,
            // Metadata required for multiple reporter
            metadata: {
                browser: {
                    name: 'Chrome',
                    version: '51'
                },
                device: 'PC',
                platform: {
                    name: 'Windows',
                    version: '8.1'
                }
            }
        },
        {
            'tunnel-identifier': tunnelID,
            build: buildNum,
            name: testRunName + '-Chrome51-Windows7',
            browserName: 'Chrome',
            version: '51.0',            
            platform: 'Windows 7',      
            screenResolution: screenResolution,
            // Metadata required for multiple reporter
            metadata: {
                browser: {
                    name: 'Chrome',
                    version: '51'
                },
                device: 'PC',
                platform: {
                    name: 'Windows',
                    version: '7'
                }
            }
        }
```

**Comment by wswebcreation** [comment]
Hi @kiche777 

Tnx for this issue. You are right. The last fix will still overwrite the JSON because the OS isn't unique enough. I didn't thought about that, manly because I see testing on Chrome Windows 7 / 8 / 10 will give the same "click" results. 

What would you suggestion be to make the filename more unique? Do all based on the `metadata` or on the basic capabilities also knowing that platform for example isn't provided when you test locally.

**Comment by kiche777** [comment]
Hi thanks for the fast response.

I'm thinking do all based on metadata for the browser and platform based on the same columns presented in the report.

When you say that platform isn't provided locally does that mean I wouldn't need this entry as it's automatically populated?  I entered platform based on example and also knowing we would be executing in SauceLabs and wasn't sure the tests would be aware.

The reason I would have great use to show the different OS is to prove coverage of that OS/Browser combination.

**Comment by wswebcreation** [comment]
Hi @kiche777 

> When you say that platform isn't provided locally does that mean I wouldn't need this entry as it's automatically populated?

When you create your capabilities in your protractor configuration file it's not a mandatory capability for running on your local machine, it is on Sauce. It tells Sauce your environment. I use this for my customer

```js
    {
        browserName: 'chrome',
        platform: "Windows 10",
        version: "latest",
        screenResolution: "1600x1200",
        name: SAUCE_NAME,
        recordScreenshots: false,
        recordVideo: false,
        'tunnel-identifier': SAUCE_TUNNEL_IDENTIFIER,
        timeZone: SAUCE_TIMEZONE,
        shardTestFiles: true,
        maxInstances: 5,
        idleTimeout: 240,
        // Cucumber specific instance options
        cucumberOpts: {
            tags: 'not (@firefox or @edge or @ie11 or @safari9 or @safari10 or @sanity-check or @mobile)'
        },
        // Custom for testing and reporting
        deviceProperties: {
            browser: {
                name: 'chrome'
            },
            device: 'Virtual Machine',
            deviceType: 'desk',
            environment: 'saucelabs',
            platform: {
                name: 'Windows',
                version: '10'
            }
        }
    }
```

I'll try to fix this tomorrow in the morning and create a new fix release. I'll then close this issue if it's fixed. I'll keep you posted

**Comment by wswebcreation** [comment]
Hi @kiche777 

I just released version 1.2.1. It will now create a file like this `foo_until_you_bar.chrome.osx.10.12.6_1506576918860.json`

Can you please verify if this is working now for you and close this issue?

Tnx in advance!

**Comment by kiche777** [comment]
Hi @wswebcreation thanks for the quick update.

The OS is now handled correctly and I can see each version of the OS listed with the browser.

Though I did find another small limitation - Same Browser but different version of the browser is also not considered unique which is confirmed by not seeing the version of the browser as part of the json file name ex.
login_to_web_hmi.Chrome.Windows.8.1_1506626470993.json

The use case here is that we want to support a range of browser versions for example Chrome 51 at a minimum up to the latest Chrome 61.  So we run against both Chrome 51 and Chrome 61 in SauceLabs to ensure changes don't break in the earlier version. 

Would you be able to handle this case as well?  Also, would you prefer I create another issue to address it?

Thanks again for the fast response/fixes.  This report looks great.

**Comment by luyen-tieu** [comment]
Hi @wswebcreation, 
I am using BrowserStack to run my protractor test, but when i put the param screenResolution: screenResolution (ex: screenResolution: "1600x1200",) to my config, my test doesn't work on correct OS platform, browser version and also screen resolution.
Could you help me?
This is my protractor config:
 {
        browserName: 'chrome',
        screenResolution: "1600x1200",
        shardTestFiles: true,
    
       deviceProperties: {
            browser: {
                name: 'chrome'
                version: '61'
            },
            device: 'Virtual Machine',
            platform: {
                name: 'Windows',
                version: '10'
            }
        }
    }
Thanks alot.

**Comment by wswebcreation** [comment]
Hi @luyen-tieu 

I never used BrowserStack, but when I search for it you need to use capabilities which can be found [here](https://www.browserstack.com/automate/capabilities).

Secondly your question is not linked to nor this question nor this module and I would advise you to ask this question on StackOverflow in the future.

Tnx in advance

**Comment by wswebcreation** [comment]
Closed this issue in favour of https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin/issues/2
