### ISSUE TITLE
What about line, branch, functions coverage??? 

### ISSUE THREAD

**Issue by ebacka** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#21]
Hello,

Probably this question is going to be deleted soon, but I didnt know where to ask about this actually. 

What about some more details like line, branch, functions coverage??? Is it possible in this plugin? I mean just telling if the test passes or fails is not enough for coverage.

Thanks,

**Comment by wswebcreation** [comment]
Hi @ebacka 

This module only transforms the Cucumber JSON to a nice report. I'd like to keep it that way, unless you can add more stuff to the cucumber JSON for all Cucumber users, then I can take a look at it
