### ISSUE TITLE
How to set custom metadata for features?

### ISSUE THREAD

**Issue by espekkaya** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#23]
**Describe your question with as much detail as possible**
I need some help for using custom meta data. You put a good [example ](https://wswebcreation.github.io/multiple-cucumber-html-reporter/browsers/index.html)for that.

There are features with custom datas generated. I want to know that how to set custom metadatas for features via one single run? I think your example shows me that you run multiple running and merge cucumber json datas. Is it right? or any other solutions for creating meta datas with running one single  running creating fetures custom meta data?

**Comment by espekkaya** [comment]
Hi @wswebcreation ,

I think we lilte confused some explanation. I have added customData but I want to set customMetadata is true and add metadata to each individual feature separately. 

`metadata: [
        {name: 'Environment v.', value: '12.3'},
        {name: 'Plugin v.', value: '32.1'},
        {name: 'Variable set', value: 'Foo'}
    ]`

I hope I explain it a little more clear :)

**Comment by wswebcreation** [comment]
Hi @espekkaya 

Sorry for my late reaction, it completely dropped off the radar. I need to check this and need to get back to you on it
