### ISSUE TITLE
HtmlReport Is not Generating :(

### ISSUE THREAD

**Issue by abubakarafzal** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#25]
**When i run the test results.json file created but i am not able to see html report ?**

**Environment (please complete the following information):**
 - protractor-multiple-cucumber-html-reporter: [1.8.0]
 - Node.js version: [v10.15.3]
 - NPM version: [6.4.1]
 - Platform name and version: [e.g. Windows 10]
 - protractor version: [Version 5.4.2]
 - Cucucmber version: [e.g. 5.1.0]
 - protractor-cucumber-framework version: [e.g. 6.1.1

]

**conf.js**
```js
const path = require('path');
exports.config = {
    directConnect: true,
    capabilities: {
        'browserName': 'chrome',
        'chromeOptions': {
        }
    },
    specs: [
           path.resolve(process.cwd(), './features/**/*.feature')
    ],
    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    cucumberOpts: {
        require: [
            path.resolve(process.cwd(), './/features/stepDefinations/stepDefinitions.js')
        ],
        format: 'json:results.json',
    },
    onPrepare: function() {
        browser.ignoreSynchronisation = true;
        browser.manage().timeouts().implicitlyWait(30000);
        browser.manage().window().maximize();
    },
    params: {
        username: 'Admin',
        password: 'Password',
    },
    plugins: [{
    package: require.resolve('protractor-multiple-cucumber-html-reporter-plugin'),
        options:{
        automaticallyGenerateReport: true,
        removeExistingJsonReportFile: true,
        }
    }],
    getPageTimeout: 30000,
    };
```

**updated question with markdown**

**Comment by wswebcreation** [comment]
Hi @abubakarafzal 

Can you also see this in your console , 

```log
=====================================================================================
    Multiple Cucumber HTML report generated in:

    /Users/wswebcreation/Git/protractor-multiple-cucumber-html-reporter-plugin/report-path/index.html
=====================================================================================

```

Because this is what I'm seeing when I run it locally

**Comment by abubakarafzal** [comment]
Thankyou now i am seeing . can you help me for taking screenshot in it :)

**Comment by wswebcreation** [comment]
You can find more info [here](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/attachments.md)

Going to close this issue now

**Comment by abubakarafzal** [comment]
Hey ,


Your repo is nicely docementated.Thankyou so much for your support . Your report isBest for protractor . Stay bless 




Get Outlook for Android







On Fri, May 17, 2019 at 4:57 PM +0500, "Wim Selles" <notifications@github.com> wrote:












You can find more info here


Going to close this issue now
