### ISSUE TITLE
Unable to get the search panel and Paginations as shown in the sample report

### ISSUE THREAD

**Issue by shivprasadkamath** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#26]
I m not able to get the search panel and paginations in the report as shown in the sample report link.
The report generated is not opened in browser by default.
this is my configuration file

```js
import {Config} from 'protractor';
import { JsonFormatter } from 'cucumber';
import * as reporter from 'cucumber-html-reporter'
import { TestObject } from 'protractor/built/driverProviders';

export let config: Config = {
  framework: 'custom',
  frameworkPath:require.resolve('protractor-cucumber-framework'),
  directConnect:true,
  capabilities: {
    browserName: 'chrome',
    metadata: {
      browser:{
          name:'Chrome',
          version: '74'
      },
      chromeOptions: {
        args: ['disable-infobars']
    },
      device:'Dell Latitude 5490',
      platform: {
          name:'Windows',
          version:'10'
      }
  },
  },
  specs: [ '../features/*.feature' ],
 // seleniumAddress: 'http://localhost:4444/wd/hub'
 SELENIUM_PROMISE_MANAGER: false,
 cucumberOpts:{
   format:'json:./cucumberreport.json',
   strict:true,
 tags:"@gofixedTest1",
//tags:"@calculatortesting",
 //tags:"@AngularTesting",

 require:[
     './stepDefinitions/*.js'
 ]
},
// Here the magic happens
plugins: [{
  package:require.resolve('protractor-multiple-cucumber-html-reporter-plugin'),
  options:{
    automaticallyGenerateReport: true,
    removeExistingJsonReportFile: true,
    customData: {
      title: 'New Automation',
      data: [
          {label: 'Project', value: 'New'},
          {label: 'Release', value: '19.1'},
          {label: 'Environment', value: 'dev01'},
          {label:'Start Time',value:new Date()},
          {label:'End Time',value:new Date()},
          {label:'Sprint',value:'Sprint 4'}
      ]
    }, 

    displayDuration:true,
    durationInMS:false,
    JsonOutputPath:'./cucumberreport.json',
    openReportInBrowser:true,
    pageFooter:'Completed',
    reportFolder:'./report',
    reportName:'New Automation',
    removeFolders:true,
    saveCollectedJSON:false,
    disableLog:false,
    pageTitle:'New Report',
  }
}]


}
```

**Environment (please complete the following information):**
 - protractor-multiple-cucumber-html-reporter: [e.g. 1.6.1]
 - Node.js version: [e.g. 8.9.1]
 - NPM version: [e.g. 5.8.0]
 - Platform name and version: [e.g. Windows 10]
 - protractor version: [e.g. 5.1.0]
 - Cucucmber version: [e.g. 4.2.0]
 - protractor-cucumber-framework version: [e.g. 6.0.0]

**Additional context**

**Updated with proper markdown**

**Comment by wswebcreation** [comment]
Can you provide a screenshot or something? This is not really helpful for me to do the debugging

**Comment by shivprasadkamath** [comment]
![report](https://user-images.githubusercontent.com/34295030/58022878-130e6a00-7b2c-11e9-936c-75460d3f0c37.JPG)
uploaded the Screen snap.There is no pagination or search in the report

**Comment by wswebcreation** [comment]
Hi @shivprasadkamath 

Hmm, that is strange, can you also provide the browser and the version of the browser that you are using to show the report?
Can you also make a screenshot of the console log of the browser, to see if there are JS-errors?

**Comment by shivprasadkamath** [comment]
Hello,

I tried on 
chrome version:74.0.3729.157
Firefox:66.0.5
Protractor version:5.1.2
![report1](https://user-images.githubusercontent.com/34295030/58074365-bc07a400-7bc2-11e9-8372-f171f470aaca.JPG)
I dont see any errors on the console log in the browser as well.

**Comment by wswebcreation** [comment]
Hmm, this is really strange

Can you zip the report and send it to me? I tried running it on my local machine and I don't get the error. So debugging the report might give me an insight where the problem is

**Comment by shivprasadkamath** [comment]
[report.zip](https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin/files/3206832/report.zip)
Hi Attaching the report.Please let me know

**Comment by wswebcreation** [comment]
@shivprasadkamath 

Thanks for the report, I've checked it and I see all the data
**Chrome 74**
![image](https://user-images.githubusercontent.com/11979740/58166933-2be16180-7c8b-11e9-9e9e-7d5d9a1f8b18.png)

**Safari 12**
![image](https://user-images.githubusercontent.com/11979740/58166997-4fa4a780-7c8b-11e9-9a46-813bf10b4261.png)

**Firefox 66**
![image](https://user-images.githubusercontent.com/11979740/58167024-5b906980-7c8b-11e9-917c-6829a9b7eece.png)


It's hard to say what the issue is

**Comment by shivprasadkamath** [comment]
thanks for the screensnaps.But i still dont get the search and pagination on chrome or firefox or any browser.
I did delete my cache and everything but still dont get it.

**Comment by wswebcreation** [comment]
@shivprasadkamath 

Can you provide a zip with your report in it, I can't seem to find the problem for you
