### ISSUE TITLE
Duplicate attachments displayed in the reporter when multiple formats are specified

### ISSUE THREAD

**Issue by slvganesh** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#29]
**Environment (please complete the following information):**
 - protractor-multiple-cucumber-html-reporter: 1.8.1
 - Node.js version: 8.11.1
 - NPM version: 5.10.0
 - Platform name and version: Windows 7
 - protractor version: 5.3.1
 - Cucucmber version: 5.1.0
 - protractor-cucumber-framework version: 6.1.2

**Config of protractor + protractor-multiple-cucumber-html-reporter**
```
const cucumObj = {
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    cucumberOpts: Object.assign({
        require: _require,
        profile: false,
        'no-source': true,
        format: [
            "./logger/protractor-html-screenshot-reporter/CucumberFormatter.js", // Custom formatter
            `json:${TEST_SUMMARY_DIR}/results/results.json`,
        ],
        print: () => { }
    }, config.protractorConfig.cucumberOpts),
    plugins: [{
            package: 'protractor-multiple-cucumber-html-reporter-plugin',
            options: {
                automaticallyGenerateReport: true,
                removeExistingJsonReportFile: true
            }
        }]
};

```
**Describe the bug**
Duplicate attachments displayed in the reporter. Here is what I am trying to attach,

`this.attach(JSON.stringify({"url": "www.google.com"}), 'application/json');`

And I'm expecting the output should be (in the reporter),
```
[
  "\"{\\\"url\\\":\\\"www.google.com\\\"}\""
]

```
But I'm getting
```
[
  "\"{\\\"url\\\":\\\"www.google.com\\\"}\"",
  "\"{\\\"url\\\":\\\"www.google.com\\\"}\""
]
```

<i>Too much of " and \ are annoying anyway. But I don't care it now</i>

When I remove my custom formatter, I do see the expected result.
```
[
  "\"{\\\"url\\\":\\\"www.google.com\\\"}\""
]

```

**Comment by slvganesh** [comment]
Apologize. I didn't notice that I was creating two instances of EventDataCollector which was causing this issue. So please close this issue.

**Comment by wswebcreation** [comment]
Thnx for the feedback
