### ISSUE TITLE
Use the browserversion in the filename

### ISSUE THREAD

**Issue by wswebcreation** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#3]
Opened this issue in favour of https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin/issues/2. That issue was fixed but there is still a bug when the same OS / browser but different browser versions are used, see below

> Though I did find another small limitation - Same Browser but different version of the browser is also not considered unique which is confirmed by not seeing the version of the browser as part of the json file name ex.`login_to_web_hmi.Chrome.Windows.8.1_1506626470993.json`

> The use case here is that we want to support a range of browser versions for example Chrome 51 at a minimum up to the latest Chrome 61. So we run against both Chrome 51 and Chrome 61 in SauceLabs to ensure changes don't break in the earlier version.

**Comment by wswebcreation** [comment]
Files should now be saved as `foo_until_you_bar.chrome.61.0.3163.100.osx.10.12.6_1506659517437.json` whith version 1.2.3

@kiche777, can you verify it and then close this issue?

**Comment by kiche777** [comment]
Confirmed the report now shows unique entries for browser version and OS.

Thanks for the fast resolution.

Closing issue as fixed and resolved for Version 1.2.3.
