### ISSUE TITLE
Report is getting generated without executing any test steps

### ISSUE THREAD

**Issue by sudhu678** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#30]
- protractor-multiple-cucumber-html-reporter: 1.8.1
 - Node.js version: 11.5.0
 - NPM version: 6.4.1
 - Platform name and version: Mac High Sierra, 10.13.6
 - protractor version: 5.4.2
 - Cucucmber version: 1.3.1
 - protractor-cucumber-framework version: 6.1.3

**Config of protractor + protractor-multiple-cucumber-html-reporter**

```js
exports.config = {
    seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    capabilities: {
        'browserName': 'chrome'
    },

    specs: [
        'features/login.feature'
    ],
    
    cucumberOpts: {
         require: './steps/login.js',
         format: 'json:.tmp/results.json'
    },
    plugins:[{
        package: 'protractor-multiple-cucumber-html-reporter-plugin',
        options:{
            automaticallyGenerateReport: true,
            removeExistingJsonReportFile: true
        }
    }]
};
```

When I comment out the format cucumber option, test steps are executed. But, report wasn't generated. If I specify format, test steps are not executed. Report shows all test steps are passed.

**Comment by wswebcreation** [comment]
Hi @sudhu678 

Can you provide a sample project, I can't reproduce it
