### ISSUE TITLE
Error reading Json

### ISSUE THREAD

**Issue by lsantos10** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#31]
The issue reported on https://github.com/wswebcreation/multiple-cucumber-html-reporter/issues/79 still happening to me even when I user release1.8.1

**Comment by lsantos10** [comment]
If I enforce o my package.json the version  1.11.6 for multiple-cucumber-html-reporter it works.

**Comment by wswebcreation** [comment]
Hi @lsantos10 

Can you please explain the problem better? I don't know what you mean. Please use the issue template to provide all the needed info, otherwise I need to close this issue
