### ISSUE TITLE
 cannot find module error

### ISSUE THREAD

**Issue by Helen109** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#32]
I have installed protractor-multiple-cucumber-html-reporter-plugin, but when I run test hit cannot find module error
![cucumberPlugin](https://user-images.githubusercontent.com/54786701/65407697-e9d15380-de15-11e9-877c-b49f972a1e40.png)

**Comment by wswebcreation** [comment]
Hi @Helen109
Can you please share you config in how you configured the module, this is not really helpfuly for debugging 😉
