### ISSUE TITLE
Embedded screen shots do not work due to Content Security Policy

### ISSUE THREAD

**Issue by Roaders** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#33]
**Environment (please complete the following information):**
 - protractor-multiple-cucumber-html-reporter: 1.8.0
 - Node.js version: 10.15.1
 - NPM version: 6.4.1
 - Platform name and version: Linux?
 - protractor version: 5.4.0
 - Cucucmber version: 5.1.0
 - protractor-cucumber-framework version: 6.1.1

**Config of protractor + protractor-multiple-cucumber-html-reporter**
```
    plugins: [
        {
            package: 'protractor-multiple-cucumber-html-reporter-plugin',
            options:{
                // read the options part for more options
                automaticallyGenerateReport: true,
                removeExistingJsonReportFile: true,
                pageTitle: "Torch Automation"
            }
        }
    ]
```

**Describe the bug**
I cannot view images when the html report is hosted in Jenkins

**Expected behavior**
I should be able to see screen shots attached to my generated report

**Log**
```
Refused to load the image 'data:image/png;base64,iVBORw0KGgoAA|| SNIP ||K5CYII=' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.myOrg.com". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Additional context**e
It seems that my Content Security Policy does not allow data urls like this. Is there an option to save the images as files and load them using a normal url?

**Comment by wswebcreation** [comment]
Hi @Roaders 

Thanks for filling an issue here, but can you file it here [`multiple-cucumber-html-reporter`](https://github.com/wswebcreation/multiple-cucumber-html-reporter/issues). 
This plugin only collects the data and it uses `multiple-cucumber-html-reporter` to generate the report.

Can you also provide which browser you are using to show the report?
