### ISSUE TITLE
Duration Time in HTML report

### ISSUE THREAD

**Issue by aszegedi** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#4]
Hi,

Could you help me out with Duration Time in the HTML report. This would be useful for me.

Thank you for your support in advance!

**Comment by wswebcreation** [comment]
Closing it in favour of https://github.com/wswebcreation/multiple-cucumber-html-reporter/issues/11

It's a feature request.

By the way. This is only the plugin that connects the dots, not the actual reporting module
