### ISSUE TITLE
Reports created only for 2 features

### ISSUE THREAD

**Issue by zac11** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#5]
I am trying to implement the `protractor-multiple-cucumber-html-reporter` plugin for my tests. My repository is [here](https://github.com/zac11/yarn-cucumber-ts).

Whenever I try to generate the reports, inspite of having more than 5+ features, the report shows only reports of only one scenario. Can you please take a look.

@wswebcreation

**Comment by wswebcreation** [comment]
Hi @zac11 

I looked into your project and you need to have a "unique" name for the feature. In your case each feature has the same name and that is not according how BDD works. If you fix that it will work.

I'm going to close it for now. It's still open for discussion.

**Comment by zac11** [comment]
@wswebcreation I updated the repo with features. I am still not able to see correct number of features v/s scenarios between what the terminal shows and the report. For example, when I run the current repo, I see

```
........................................................

7 scenarios (7 passed)
21 steps (21 passed)
0m50.071s


=====================================================================================
    Multiple Cucumber HTML report generated in:

    C:\Users\Rahul Yadav\Documents\yarn-cucumber-ts\reports\report\index.html
=====================================================================================
```

However, the results in the HTML are generated for 6 features but 10 scenarios.  Can you take a look if I am still not doing something correctly with the features.

Thanks 👍

**Comment by wswebcreation** [comment]
Hi @zac11 

When I checkout your project I get this

```shell
$ protractor --baseUrl https://angular.io
[13:54:31] I/launcher - Running 1 instances of WebDriver
[13:54:31] I/direct - Using ChromeDriver directly...
........................................................

7 scenarios (7 passed)
21 steps (21 passed)
0m29.877s

 
=====================================================================================
    Multiple Cucumber HTML report generated in:
    
    /Users/wswebcreation/contributions/yarn-cucumber-ts/reports/report/index.html
=====================================================================================

[13:55:03] I/launcher - 0 instance(s) of WebDriver still running
[13:55:03] I/launcher - chrome #01 passed
✨  Done in 37.13s.
```

And this it the report
![image](https://user-images.githubusercontent.com/11979740/31545153-7f6c2654-b01e-11e7-8d9f-e7563603c815.png)

Looks like all data is correct
