### ISSUE TITLE
Screenshots- Error------------ TypeError: this.attach is not a function

### ISSUE THREAD

**Issue by subhavani** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#8]
How to attach screenshots to test report? 
Trying this  : 

```js
 After(async function (scenario) {
    
if (scenario.stepsResults !== 'FAILED') {
      
// screenShot is a base-64 encoded PNG
      
const screenShot = await browser.takeScreenshot();
      
this.attach(screenShot, 'image/png');
    
}
  
});
```

**Comment by wswebcreation** [comment]
This should do the trick https://github.com/wswebcreation/multiple-cucumber-html-reporter#how-to-attach-screenshots-to-html-report

**Comment by subhavani** [comment]
Thanks for the quick response.

Will check it out. Hope this would attach the screenshots to the html report

**Comment by subhavani** [comment]
sorry , but in this, what is screenshot, on which we are caling replace?

const decodedImage = new Buffer(screenshot.replace(/^data:image\/
png;base64,/, ''), 'base64');

**Comment by subhavani** [comment]
tried as below:

After(async function (scenario) {
browser.driver.takeScreenshot().then((screenshot) => {
const decodedImage = new Buffer(screenshot.replace(/^data:image\/
png;base64,/, ''), 'base64');
scenario.attach(decodedImage, 'image/png');
});

got this error:

: Property 'attach' does not exist on type 'HookScenarioResult'. (2339)

**Comment by wswebcreation** [comment]
@subhavani 

You are using TypeScript? If so, please check [this for CucumberJS 2](https://github.com/wswebcreation/protractor-cucumber-typescript-boilerplate/blob/2.x/e2e-tests/config/helpers/after.scenario.ts) and [this for CucumberJS 3](https://github.com/wswebcreation/protractor-cucumber-typescript-boilerplate/blob/master/e2e-tests/config/helpers/after.scenario.ts). Those are my boilerplates.

**Comment by subhavani** [comment]
thanks , but my need is to make the screenshot appear as a link on the
cucumber html report

**Comment by edgarechm** [comment]
I am using Protractor and have a similar issue:

This is my hoos.js file:
```
const {After} = require('cucumber');
	
	After(function(scenario) {
		if(scenario.isFailed()){
			return driver.takeScreenshot()
				.then(function (buffer) {
					const decodedImage = new Buffer(screenshot.replace(/^data:image\/png;base64,/, ''), 'base64');
					scenario.attach(decodedImage, 'image/png');
				});
		}
	});
```

- "chromedriver": "2.33.2",
- "cucumber": "4.2.1",
- "protractor": "5.1.2",
- "protractor-cucumber": "0.1.8",
- "protractor-cucumber-framework": "5.0.0",
- "protractor-multiple-cucumber-html-reporter-plugin": "^1.7.0",
- "selenium-server-standalone-jar": "3.4.0"

This is the error:
 ```
× After # support\hooks.js:13
       TypeError: scenario.isFailed is not a function
           at World.<anonymous> (C:\workspace\project\support\hooks.js:14:15)

```
